//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class Consts
{
	public static SignalRPath: string = `/MessageHub`;
	public static MessageReceivedString: string = `MessageReceivedString`;
	public static JoinString: string = `JoinString`;
	public static SendMesssageString: string = `SendMesssageString`;
	public static SetActionsString: string = `SetActionsString`;
	public static SetActionString: string = `SetActionString`;
	public static PerformActionString: string = `PerformActionString`;
	public static StatePostString: string = `StatePostString`;
}
