//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IMessage } from '../../dal/Models/IMessage';
import { IAction } from '../IAction';

export class State
{
	public messages: IMessage[];
	public statuses: any[];
	public actions: IAction[];
}
